INSERT INTO city("city_name", "created_at", "updated_at") VALUES
('RINCAO', now(), now()),
('SAO CARLOS', now(), now()),
('CAMPINAS', now(), now()),
('ARARAQUARA', now(), now()),
('RIBEIRAO BONITO', now(), now()),
('RIBEIRAO PRETO', now(), now()),
('GUATAPARA', now(), now()),
('SANCA LUCIA', now(), now()),
('AMERICO BRASILIENSE', now(), now()),
('AMERICANA', now(), now()),
('CRAVINHOS', now(), now()),
('RECIFE', now(), now()),
('NATAL', now(), now()),
('MACEIO', now(), now()),
('RIO DE JANEIRO', now(), now()),
('SAO PAULO', now(), now()),
('SERTAOZINHO', now(), now()),
('LINS', now(), now()),
('SAO JOSE DO RIO PRETO', now(), now()),
('SAO JOSE DOS CAMPOS', now(), now()),
('SOROCABA', now(), now()),
('SUMARE', now(), now());